// examples/vue/src/App.vue
<script setup lang="ts">
import Button from "./components/Button.vue";

const intents = [undefined, "primary", "secondary"] as const;
const sizes = [undefined, "medium", "small"] as const;
</script>

<template>
  <table class="variant-table">
    <thead>
      <tr>
        <th></th>
        <th v-for="intent in intents">
          {{ intent || "default" }}
        </th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="size in sizes">
        <th scope="row">{{ size || "default" }}</th>

        <td v-for="intent in intents">
          <Button :intent="intent" :size="size"
            >{{ intent || "default" }} button
          </Button>
        </td>
      </tr>
    </tbody>
  </table>
</template>

<style scoped>
.variant-table {
  position: relative;
  height: max-content;
  width: max-content;
  align-self: center;
  justify-self: center;
}

.variant-table :where(th, td) {
  padding: 0.5rem;
}
</style>

// examples/svelte/src/App.svelte
<script lang="ts">
  import Button from "./components/button.svelte";

  const intents = [undefined, "primary", "secondary"] as const;
  const sizes = [undefined, "medium", "small"] as const;
</script>

<table class="variant-table">
  <thead>
    <tr>
      <th />
      {#each intents as intent}
        <th scope="col">{intent || "default"}</th>
      {/each}
    </tr>
  </thead>
  <tbody>
    {#each sizes as size}
      <tr>
        <th scope="row">{size || "default"}</th>
        {#each intents as intent}
          <td>
            <Button {...intent && { intent }} {...size && { size }}>
              {intent || "default"} button
            </Button>
          </td>
        {/each}
      </tr>
    {/each}
  </tbody>
</table>

<style>
  .variant-table {
    position: relative;
    height: max-content;
    width: max-content;
    align-self: center;
    justify-self: center;
  }

  .variant-table :where(th, td) {
    padding: 0.5rem;
  }
</style>
